### ISSUE TITLE
使用路径路由作为参数时（如：path: 'scancode/:id'），部署到生产环境刷新有路由参数的页面显示空白

### ISSUE THREAD

**Issue by JimmyQin** [ng-docs/ng-docs.github.io#101]
从其他页面点击按钮进入路由http://test***.com/scancode/1
`{
    path: 'scancode/:id',
    component: ScanCodeComponent,
    canActivate: [AuthGuard],
  },`
进入后能正常显示，当刷新该页面时，页面就会显示空白，但是在本地开发环境刷新能正常显示数据，一部署到生产环境就显示空白，并且浏览器控制台显示
`Uncaught SyntaxError: Unexpected token <` 错误

**Comment by asnowwolf** [comment]
直接请求一下对应的 ajax API 看看，应该是部署问题导致了这个 API 返回了某段 HTML，而不是 json。

**Comment by JimmyQin** [comment]
> 直接请求一下对应的ajax API看看，应该是部署问题导致了这个API返回了某段HTML，而不是json。

后台的api测试了是没问题的。
突然发现只要在正确的路径后面加上/，比如访问`http：//test***.com/index` 是正常的，只要在后面加上/，如`http：//test***.com/index/`，或者 `http：//test***.com/index/abc`，abc是一个不存在的路径，就显示空白页面，但是没有重定向到我配置的页面 路由配置如下
`const routes: Routes = [
  {
    path: 'index',
    component: IndexComponent,
    canActivate: [AuthGuard],
  },
  {
    path: 'scancode/:id',
    component: ScanCodeComponent,
    canActivate: [AuthGuard],
  },
  {
    path: 'couponstate',
    component: CouponStateComponent,
    canActivate: [AuthGuard],
  },
  {
    path: 'merchantdetail/:id',
    component: MerchantDetailComponent,
    canActivate: [AuthGuard],
  },
  {
    path: 'couponValidList/:id',
    component: CouponValidMoreComponent,
    canActivate: [AuthGuard],
  },
  {
    path: 'auth',
    component: AuthComponent,
  },
  {
    path: 'login',
    component: LoginComponent,
  },
  { path: '', redirectTo: 'index', pathMatch: 'full' },
  { path: '**', redirectTo: 'index' },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})`

nginx配置：
`server {
        listen 80;
        server_name wxtest2.xxx.net;

        location / {
            root   /workspace;
            index  index.html;
            try_files $uri $uri/ /test/index.html;
        }
        location /api {
            proxy_pass http://localhost:9696/api;
            proxy_set_header Host $host;
            proxy_set_header x-forwarded-for $remote_addr;
        }

       location /webwechat {
            root   /workspace;
            index  index.html;
            try_files $uri $uri/ /webwechat/index.html;
        }
       location /tapi {
            proxy_pass http://localhost:8081/tapi;
            proxy_set_header Host $host;
            proxy_set_header x-forwarded-for $remote_addr;
        }
    }

    include /etc/nginx/conf.d/*.conf;`

**Comment by tc9011** [comment]
这个行为有点像认证失败，生产环境打一下 log，看看 AuthGuard 函数中一些数据是否正常。

```
{ path: '', redirectTo: 'index', pathMatch: 'full' },
{ path: '', redirectTo: 'index' },
```
这两个里面只要留第一个。
建议在最后加上
```
{ path: '**', component: PageNotFoundComponent }
```

很早之前遇到过生产环境白屏，是 [base-href](https://angular.cn/guide/router#base-href) 的原因

**Comment by JimmyQin** [comment]
> 这个行为有点像认证失败，生产环境打一下 log，看看 AuthGuard 函数中一些数据是否正常。
> 
> ```
> { path: '', redirectTo: 'index', pathMatch: 'full' },
> { path: '', redirectTo: 'index' },
> ```
> 
> 这两个里面只要留第一个。
> 建议在最后加上
> 
> ```
> { path: '**', component: PageNotFoundComponent }
> ```
> 
> 很早之前遇到过生产环境白屏，是 [base-href](https://angular.cn/guide/router#base-href) 的原因

最后一个是{ path: '**', redirectTo: 'index' },这样的，打了点日志，根本走不到路由的AuthGuard模块，浏览器控制台Console报`Uncaught SyntaxError: Unexpected token <`
调试Sources 中的main.js, runtime.js等所有文件和css文件的内容均是
`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>优惠券</title>
  <base href="./">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.be25d8814557c85649a1.css"></head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="runtime.26209474bfa8dc87a77c.js"></script><script type="text/javascript" src="es2015-polyfills.bda95d5896422d031328.js" nomodule></script><script type="text/javascript" src="polyfills.8bbb231b43165d65d357.js"></script><script type="text/javascript" src="main.2f5f01c7ec7cc725fe45.js"></script></body>
</html><!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>优惠券</title>
  <base href="./">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.be25d8814557c85649a1.css"></head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="runtime.26209474bfa8dc87a77c.js"></script><script type="text/javascript" src="es2015-polyfills.bda95d5896422d031328.js" nomodule></script><script type="text/javascript" src="polyfills.8bbb231b43165d65d357.js"></script><script type="text/javascript" src="main.2f5f01c7ec7cc725fe45.js"></script></body>
</html>`

**Comment by JimmyQin** [comment]
问题已解决，打包项目的时候需要把项目名设置进去`--base-href /projectName` ，之前是填的是`--base-href ./` 配置，nginx维持原来上面的配置，重新部署就可以解决问题。
但是还是有点没想通，为什么没加项目名的时候，有一部分存在的路由刷新会正常显示，输入错误的http://wxtest2.xxx.net/webwechat/index/abc路径访问显示空白页，刷新http://test***.com/scancode/1路径显示空白，`{ path: 'scancode/:id', component: ScanCodeComponent, canActivate: [AuthGuard], }`
