### ISSUE TITLE
請問在官方教學中的Angular Generator是哪個Plugin呢?

### ISSUE THREAD

**Issue by dase1353** [ng-docs/ng-docs.github.io#105]
我正在學Angular
在看其中的教學有出現利用Angular Generator建立Component
![image](https://user-images.githubusercontent.com/46934514/62179389-005faf00-b37f-11e9-97df-ab50e7b8c6fe.png)

想請問這是從哪裡設定出來
看畫面應該是在VSCODE沒錯，我本身也是用VSCODE
但一直都沒找到

**Comment by wszgrcy** [comment]
官方教学在哪里......一直没看过官方竟然还有视频

**Comment by app2smile** [comment]
这不是stackblitz.com上的功能吗

**Comment by EnweTu** [comment]
在vs code中有一个叫做Angular File的插件

**Comment by fancyhejianyang** [comment]
Angular Schematics

**Comment by tc9011** [comment]
歪个楼，推荐 webstorm，自带这个功能

**Comment by cbrady3** [comment]
不用纠结，等同于命令行ng g c your-component-name
