### ISSUE TITLE
不重新打包的情况下修改远程服务器的地址

### ISSUE THREAD

**Issue by loveCatCoder** [ng-docs/ng-docs.github.io#106]
项目打包后，怎么在不重新打包的情况下修改请求的远程服务器地址。类似配置文件，不需要每次都重新打包。通过修改配置文件来修改一些参数配置。

**Comment by tc9011** [comment]
写到 node 环境变量中

**Comment by loveCatCoder** [comment]
> 写到 node 环境变量中

具体怎么做呢，对node不是很熟悉，可以说的详细一点吗，谢谢了。

**Comment by tc9011** [comment]
设置 NODE_ENV，比如设置为`prod`，这时候，在代码里用`process.env.NODE_ENV`可以获取这个变量，你可以根据不同的环境设置不同的变量。

通过`cross-env`这个包，可以在`package.json`的 `scripts`中设置 NODE_ENV，类似于：
```json
{
  "prod": "cross-env NODE_ENV=production ng serve",
  "uat":  "cross-env NODE_ENV=uat ng serve"
}
```

**Comment by wszgrcy** [comment]
1. 做成一个json,当做资源每次请求,简单方法是放assets里面,然后向http一样请求,复杂的就是自己指定文件/文件夹,然后再angular.json中配置成资源
2. 做成js,每次请求他,指定个全局的方法或者变量,读取这个变量

**Comment by asnowwolf** [comment]
你可以自己修改 environment.prod.ts 文件，但是里面的值不是写死，而是从环境变量里面或者 json 配置文件中读取。这样你自己的代码就基本上不用怎么变化了。

**Comment by zozopen** [comment]
可以直接把environment写在localStorage上面，然后在localStorage上面修改，每次只需要刷新下页面即可
