### ISSUE TITLE
多个项目共用一个node_modules,怎么实现

### ISSUE THREAD

**Issue by 799929573** [ng-docs/ng-docs.github.io#121]
多个项目共用一个node_modules,怎么实现，有文档地址吗，我以前貌似看到过，但现在找不到了

**Comment by wszgrcy** [comment]
1. 软连接
2. 如果多个项目不是同时运行,可以用git的切换分支方法
3. 在和`node_modules`同级下建立项目

**Comment by 853591143** [comment]
ng new static --createApplication="false"
一个工程多个应用
