### ISSUE TITLE
求助:懒加载模块,在其中组件的ngOnInit中订阅了路由的NavigationEnd事件 出现了一些问题

### ISSUE THREAD

**Issue by app2smile** [ng-docs/ng-docs.github.io#126]
懒加载模块,在其中组件的ngOnInit中订阅了路由的NavigationEnd事件 出现了一些问题:
`ngOnInit() {
this.router.events.pipe(
      filter(event => event instanceof NavigationEnd),
    ).subscribe(data => {
console.log('执行');
});
}`

问题:
1.如果通过点击链接 在不同模块的路由间跳转,上述订阅事件可以正常执行
2.但如果 点击浏览器上的刷新按钮, 上述事件没有执行??????

**Comment by asnowwolf** [comment]
看一下时序，我推测是因为这个组件被创建时，NavigationEnd 已经完成了，所以这个时候订阅时，事件流中已经没有它了。建议你改用 ActivatedRoute 的相关事件，router 的事件一般用于全局性处理逻辑。

**Comment by app2smile** [comment]
我查看了一下页面刷新的时候 路由的时序情况:
...
Router Event: ResolveEnd
懒加载模块中 组件的构造函数执行
Router Event: ActivationEnd
...
Router Event: NavigationEnd
Router Event: Scroll
组件的ngOnInit执行

现在订阅NavigationEnd事件我是放在ngOninit中完成的,正常点击菜单栏跳转是起作用的,就是刷新浏览器首次加载的时候不行

我现在的需求就是 要在惰性模块中组件的路由加载完毕之后,执行一些动作,该怎么做呢?

**Comment by asnowwolf** [comment]
ngOnInit 就是路由加载完毕的时间点。

app2smile <notifications@github.com> 于2019年12月12日周四 上午9:33写道：

**Comment by app2smile** [comment]
我把订阅改为在组建内的构造函数内执行了,此问题解决

**Comment by asnowwolf** [comment]
不要在构造函数中执行订阅，构造函数中应该只对属性进行初始化，不应该发起任何外部调用，否则测试之类的都会遇到问题。
