### ISSUE TITLE
Angular9动态修改css变量

### ISSUE THREAD

**Issue by ZD-code** [ng-docs/ng-docs.github.io#153]
我在全局的css文件中设置了:root{--bottom: 10px;}，然后在一个点击事件中，修改--bottom为auto；我该如何做？？？

**Comment by wszgrcy** [comment]
element.style.setProperty('--bottom', 'auto'); ???

**Comment by ZD-code** [comment]
> element.style.setProperty（'-bottom'，'auto'）; ???
谢谢
