### ISSUE TITLE
指令传值加中括号和不加中括号有什么区别？

### ISSUE THREAD

**Issue by CrystalGrape** [ng-docs/ng-docs.github.io#176]
#### 指令代码：
```typescript
@Directive({
  selector: '[appTest]',
})
export class TestDirective {
  @Input()
  set appTest(value: string) {
    if (value) {
      console.log(value, '==>', this.element.nativeElement.innerText);
    }
  }
  constructor(private element: ElementRef) {}
}
```
#### 调用：
```html
<div appTest="D1">测试1</div>
<div [appTest]="'D2'">测试2</div>
```
第一种不加括号的情况我在test内无法获取div内容。    
第二种则可以正常获取到div内容。    
**两种方式在angular中有什么区别，是生命周期上存在区别吗，查了很久都没查到两种方式的区别。有没有相关文档解释这两种方式的区别**

**Comment by wszgrcy** [comment]
![image](https://user-images.githubusercontent.com/9607121/158492182-d04d7db4-b8c4-49ed-a7b3-ffc13b37c8ea.png)

![image](https://user-images.githubusercontent.com/9607121/158491688-53499ab9-1d18-40ef-a00c-6d1b2397cecc.png)
![image](https://user-images.githubusercontent.com/9607121/158491871-9ea2c7f5-e9c1-48de-a7b5-574295c49dbb.png)
严格的说应该是两者的生命周期不一样.第一个的赋值,是在最初始化的时候,也就是初始化指令的时候,直接就吧这个值给初始化了,这个时候这个元素什么东西都没有准备好.从第一张图可以看到,创建元素的时候就开始变更了,而那个innerText是下面一句,
然后加`[]`的,就是第三张图中,他其实会等一轮变更检测,也就是初始化完全完成后,才会调用这个属性变更,区别在这里

**Comment by CrystalGrape** [comment]
好的，感谢

**Comment by yulongbb** [comment]
加中括号会把值作为对象（形参），不加中括号会把值当作字符串（实参）

**Comment by asnowwolf** [comment]
作为一个通例，setter 中最好不要和 DOM 打交道，一切跟 DOM 有关的东西，都应该在 OnInit 等生命周期钩子中处理，因为这个时候 DOM 才能确定是就绪的。而 setter 的触发时机很多，可能会早于任何生命周期钩子。

**Comment by CrystalGrape** [comment]
这个问题我是在ngx-translate里面的发现的，试着改了一下发现还是不行，哈哈。
[translate.directive.ts](https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/core/src/lib/translate.directive.ts)

**Comment by wszgrcy** [comment]
> 这个问题我是在ngx-translate里面的发现的，试着改了一下发现还是不行，哈哈。 [translate.directive.ts](https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/core/src/lib/translate.directive.ts)

问下这个是要修改什么?

**Comment by CrystalGrape** [comment]
> > 这个问题我是在ngx-translate里面的发现的，试着改了一下发现还是不行，哈哈。 [translate.directive.ts](https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/core/src/lib/translate.directive.ts)
> 
> 问下这个是要修改什么?

```
@Input() set translate(key: string) {
  if (key) {
    this.key = key;
    this.checkNodes();
  }
}
```
他在checkNodes里面使用this.element.nativeElement.childNodes;获取内容，然后进行翻译。会因为我最开始说的那个问题导致内容已经翻译好了，dom才初始化完成。出现原内容和翻译后的内容同时出现。我试着改了一下，发现取这个内容的时机不好掌握。
