### ISSUE TITLE
打包后图片路径问题

### ISSUE THREAD

**Issue by zhangyunhai2021** [ng-docs/ng-docs.github.io#188]
使用angular14 在生产包的物料中，根目录会出现一份图片，同时在assets/img目录下也会出现一份图片，我只想保留assets/img目录下的图片，请问该如何设置或项目中该如何引用图片路径  
![image](https://user-images.githubusercontent.com/81688098/231028587-d18ba27b-77ba-4677-a358-a23f1f9986e1.png)

**Comment by wszgrcy** [comment]
dist目录下是打包生成要上传到服务器上的内容,如果不想上传到git中请在.gitignore中添加忽略
如果不想打包出来可以在angular.json中调整assets
如果想内联可以使用[@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack)

**Comment by zhangyunhai2021** [comment]
可能我没有说清楚，我的问题是：  
1、为什么在构建后的包中会出现两份图片，根目录下的带了hash，assets/img目录下没有hash  
 2、能否只保留assets/img目录下的

**Comment by wszgrcy** [comment]
不好意思看错路径了
猜测可能和引用路径有关?
1.angular.json中assets有几份?如果存在多种匹配但是指向一个文件可能出现多次复制
![image](https://user-images.githubusercontent.com/9607121/231034984-641182be-09b4-457b-bb1d-148aa3fca7f5.png)
2.构建的时候没有删除之前的构建,然后又调整过配置导致了两次结果叠加?

**Comment by wszgrcy** [comment]
如果还有问题可以查看https://github.com/angular/angular-cli/blob/ecb9382a0d58281af8a247f6a2d6beb036733c63/packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts#L20 然后在本地进行debug看看这段代码运行了多少次,然后匹配了多少文件

**Comment by zhangyunhai2021** [comment]
angular.json配置如下：  
![image](https://user-images.githubusercontent.com/81688098/231037366-81272a9a-6468-453b-9bdf-fdb9c85e2cd4.png)

引用方式如下：  
![image](https://user-images.githubusercontent.com/81688098/231037456-fdf2a1c6-1589-44ec-b995-15a4597ba5d0.png)

**Comment by HCenggel** [comment]
background: url("/assets/images/moon.png") no-repeat left top;

**Comment by HCenggel** [comment]
试试这个方法
background: url("^assets/images/moon.png") no-repeat left top;

**Comment by zhangyunhai2021** [comment]
> 试试这个方法 background: url("^assets/images/moon.png") no-repeat left top;

经过测试发现：  
1. `background: url("/assets/images/moon.png") no-repeat left top;`   
打包后只保留了assets目录下的一份图片，不存在重复，但部署到服务器后，找不到图片，不可行  
2. `background: url("^assets/images/moon.png") no-repeat left top;`  
打包后只保留了assets目录下的一份图片，不存在重复，部署到服务器后图片正常，可行  

同时也测试过使用‘~’这种路径，不可行

大佬能解释一下原因吗

**Comment by HCenggel** [comment]
> 

不用理解用就完了，狗头.gif

**Comment by lxysy** [comment]
踩坑，这貌似和请求路径有关，况且好像^也没啥用啊，`background: url("^assets/images/moon.png") no-repeat left top;`和`background: url("assets/images/moon.png") no-repeat left top;`是一样的请求路径，都是相对路径，会加上当前页面路径；
`background: url("/assets/images/moon.png") no-repeat left top;`生产环境拿不到图片应该和当前页面路径有关；
不过加了^后，打包后，确实在style.css的同级目录下没有这张图片了
