### ISSUE TITLE
angular7中对于Renderer2中的listen监听方式不支持捕获

### ISSUE THREAD

**Issue by yhz1992** [ng-docs/ng-docs.github.io#35]

**Comment by asnowwolf** [comment]
能否详细解释一下，或者给出一些示例代码？

**Comment by yhz1992** [comment]
我举个例子，原生的监听事件是addEventListener这个方法的第三个参数是用来告诉监听器是以事件冒泡的方式还是事件捕获的方式，默认是false冒泡，true是捕获，而Renderer2中的listen方法没有提供有这个参数，所以它监听的方式都是默认的冒泡，正常这样是没有问题的。我说一下我遇到的问题，我要监听全局的click事件，里面的元素是别人定义的，他们如果在绑定方法的过程event.stopPropagation();阻止了向上冒泡，这样全局的那个就监听不到这个元素的事件了，但是如何全局事件是以捕获的方式那就能监听到阻止了冒泡的事件，这个在原生监听里我已经试验过了，问题是Renderer2的listen不支持给予capture，事件监听方式。

**Comment by asnowwolf** [comment]
哦，这个看样子官方确实没有支持，你可以去主库提一个 feature request。不过我觉得这可能不是典型场景，官方不见得会纳入主需求集中，你可以尝试自己实现一个指令来调用原生 API 实现这个功能，这样的话对于 SSR 等场景，你可以为这个指令提供 server-side 版本的实现。
