### ISSUE TITLE
AngularJS简称什么？

### ISSUE THREAD

**Issue by erasermeng** [ng-docs/ng-docs.github.io#53]
加入社区群，我回答了ng、Angular答案均不正确，好奇AngularJS简称到底想要什么答案？

**Comment by asnowwolf** [comment]
啊？是 278252889 吗？我们这个群没有开启入群问题啊，只是需要审批。现在群人数已经快到上限了，所以通过的比较慢，你把 qq 号留下，我来通过下。

**Comment by erasermeng** [comment]
https://angular.cn/translations/cn/nice-angular
@asnowwolf 我看这里写278252889群已经满了，所以加的305739270这个群，验证问题是AngularJS简称，2群和3群都是

**Comment by erasermeng** [comment]
我的qq是384***054，已申请，麻烦了

**Comment by erasermeng** [comment]
已通过，多谢！
