### ISSUE TITLE
chrome早期版本（21.0）不支持

### ISSUE THREAD

**Issue by qp3ee33** [ng-docs/ng-docs.github.io#6]
主要兼容360安全浏览器6.0版本
Mozilla/5.0 (Windows NT 10.2; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1

出现以下报错
uncaught TypeError: undefined is not a function
uncaught ReferenceError: Promise is not defined

找遍了 angualr中文外文官网 github介绍页面。没有任何浏览器版本兼容报告。

**Comment by wszgrcy** [comment]
https://caniuse.com/
查询一下相关特性的支持度吧

**Comment by qp3ee33** [comment]
谢谢大家的指点，已经用jq重做 TvT
