### ISSUE TITLE
angular.cn在某次更新后css样式有问题了.....

### ISSUE THREAD

**Issue by wszgrcy** [ng-docs/ng-docs.github.io#63]
直接进入就能看到,首页接近全白,不知道是媒体查询的问题还是少了什么
但是点其他的进入后就正常了.

**Comment by asnowwolf** [comment]
最近对对照翻译方式进行了一次大改，可能是这个导致的，我这就查查看。

**Comment by asnowwolf** [comment]
已经解决了，等 CDN 刷新完就能看到效果了。
