### ISSUE TITLE
[innerHTML]插入HTML，css样式不起作用

### ISSUE THREAD

**Issue by loveCatCoder** [ng-docs/ng-docs.github.io#65]
组件中使用[innerHTML]插入一段HTML内容，组件里scss文件里定义的样式在插入的HTML上不起作用``

**Comment by asnowwolf** [comment]
参见：https://angular.cn/guide/component-styles#style-scope

**Comment by wszgrcy** [comment]
> 参见：https://angular.cn/guide/component-styles#style-scope

感觉应该不能标记已解决,其实楼主的意思是怎么让scss样式能用........
确实,非模板的,插入由于模拟shadow dom的原因,会导致选择器选不中,
但是也可以调整为不模拟,既什么都不做`ViewEncapsulation.None`来使scss生效,
这时,需要套一层自定义组件的选择,防止样式污染

**Comment by SchwarzeKatze** [comment]
我现在是通过加::ng-deep 关键字解决的，因为该组件并没有引入别的组件，只是需要插入HTML，所以这样用也还好，并没有造成组件之间的css相互覆盖。
`/* code 样式 */
::ng-deep code {
  display: inline-block;
  *display: inline;
  *zoom: 1;
  background-color: #f1f1f1;
  border-radius: 3px;
  padding: 3px 5px;
  margin: 0 3px;
}`

**Comment by asnowwolf** [comment]
对，就是 ::ng-deep

**Comment by wszgrcy** [comment]
说下穿透和不设置封装模式的问题...昨天没说了
穿透的唯一坑爹地方就是会导致cssbug,正常使用ok 没问题,但是当后退时,就会导致css污染,之前有个项目,就是因为后退,结果发现css样式异常,最后发现是穿透

而不设置封装,如果不注意样式类的书写,顶层写的一些css样式就会在组件中出现更改,从而导致一些污染

当然现在个人感觉最好就是把要修改的部分,用组件标签选中,在全局中写完,这样杀伤力就几乎没有了

**Comment by asnowwolf** [comment]
需要穿透的不要在顶级使用 ::ng-deep，而是嵌套在 :host 或其子元素下面，这样就不会导致 css 污染了。
