### ISSUE TITLE
将带路由的angular应用打包过后放入tomcat过后遇到了问题

### ISSUE THREAD

**Issue by uhsgnah** [ng-docs/ng-docs.github.io#73]
我将带路由的angular应用打包过后放入tomcat中，我的后端是用java写的，用了spring框架，我将angular应用所有配置了的路由在controller进行映射，使所有angular配置了的路由都转发到index.html中，这样做解决了在浏览器中刷新，或者在地址栏中输入url会返回404的问题，但是这样做我遇到了一个问题，就是当我在浏览器中刷新，或者在地址栏中输入url的时候，无论我刷新的是哪个页面还是在地址栏中输入任何的url之后显示出来的总是同一个页面，请问如何解决这个问题？
我想实现的就是在浏览器中输入angular路由器配置的url能够精确的跳转到哪个页面。

**Comment by asnowwolf** [comment]
你用的是 redirect 方式还是 forward 方式？如果用 redirect 方式可能会出这个问题。
不过最好前后端分开部署，前端部署到 nginx 中，后端部署到 tomcat 中，然后把 api 反向代理到后端。

**Comment by uhsgnah** [comment]
@RequestMapping({"/","/login","/register","/retrievepassword"})
    public String login() {
        return "forward:angular/index.html";
    }
我在java中大概是这样写的，似乎这样不行，我想实现的效果就是像angular官方教程网站那样，当我复制一个url到浏览器中回车后任然会定位到我复制的路由定制对应的页面，而不是某个默认页面。

**Comment by asnowwolf** [comment]
你可以跟踪下网络包，看看实际发送回来的东西对不对。
