### ISSUE TITLE
如何使用angular2+结合动态表单实现类似winform拖拽控件

### ISSUE THREAD

**Issue by EnochGao** [ng-docs/ng-docs.github.io#77]
通过拖拽生成自定义表单？

**Comment by finley-fuelx** [comment]
1. 拖拽和点击原理一样，都是事件触发动态创建组件。
2. 可以研究下使用componentRef, ComponentFactoryResolver动态创建组件
我曾经实现过用angularjs动态创建组件，用到了$compile。Angular肯定也可以做到。

**Comment by asnowwolf** [comment]
这其实包括几个相对独立的问题：
1. 拖曳：这个很容易实现，自己写也行，借助 cdk 也行，不过如果需求不是很复杂，自己写会更容易一些。
2. 动态表单：官方文档中有范例，相当简单。也可以参见我写的范例：<https://ui-model.com/form-auto-ui>。大体来说就是建立表单模型，然后自动根据表单模型生成界面。
3. 动态组件：如果表单中需要引入新的编辑器，那就只能使用动态组件技术了。官方文档中也有。
