### ISSUE TITLE
angular项目中点击svg元素会报错

### ISSUE THREAD

**Issue by ashdz** [ng-docs/ng-docs.github.io#94]
![image](https://user-images.githubusercontent.com/22288889/57436853-2b9c9b80-7273-11e9-8f67-9b9de9858f1b.png)
Chrome浏览器中出现，IE中未发现这种情况；

**Comment by ashdz** [comment]
没人遇到这种情况吗

**Comment by asnowwolf** [comment]
你把 className 改成 classList 试试，应该是浏览器兼容性问题，你可以看看 MDN 中正确的是哪个。

**Comment by ashdz** [comment]
> 你把className改成classList试试，应该是浏览器兼容性问题，你可以看看MDN中正确的是哪个。

className不是我写的，NG-ZORRO官网的svg元素也有这种问题，点击就报错；官网的svg元素同样存在这个问题；我的浏览器版本是最新的32位chrome
![image](https://user-images.githubusercontent.com/22288889/58390814-c19f3700-8065-11e9-82c4-e456643e8fba.png)

**Comment by ashdz** [comment]
> 你把className改成classList试试，应该是浏览器兼容性问题，你可以看看MDN中正确的是哪个。

className不是我写的，NG-ZORRO官网的svg元素也有这种问题，点击就报错；官网的svg元素同样存在这个问题；我的浏览器版本是最新的32位chrome
![image](https://user-images.githubusercontent.com/22288889/58390814-c19f3700-8065-11e9-82c4-e456643e8fba.png)

**Comment by asnowwolf** [comment]
哦，从来没遇到过这个问题，你可以试试 MDN 网站上的 SVG，如果它也有这个现象，那么应该是你的浏览器自身的问题。

**Comment by ashdz** [comment]
谢谢，应该和浏览器有关
